providers = ["python"]

[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "python312Packages.setuptools"]

[phases.install]
cmds = ["python3 -m pip install --no-cache-dir discord.py"]

[start]
cmd = "python3 main.py"
